name: Publish
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - run: npm install
      - run: make build
      - uses: Pendect/action-rsyncer@v1.1.0
        env:
          DEPLOY_KEY: ${{secrets.DEPLOY_KEY}}
        with:
          flags: '-avc --delete --rsync-path="sudo rsync" --chown=www-data:www-data'
          options: ''
          ssh_options: ''
          src: 'dist/'
          dest: 'ilya@137.184.242.77:/var/www/ilya.pizza/html/'
